import { Patient, DoctorProfile, ClinicSettings, EmailConfig, Appointment } from '../types';

export const initialDoctor: DoctorProfile = {
  name: 'Dr. Shweta N. Sawant',
  qualifications: 'B.A.M.S | Ayurveda & Panchakarma Consultant',
  specialisation: 'Ayurveda & Panchakarma Specialist',
  medicalLicenseNo: 'I-107200-A',
  email: 'vaidyashwetaayurveda@gmail.com',
  contact: '9067251670',
  photoUrl: '',
};

export const initialClinic: ClinicSettings = {
  name: "Dr. Shweta's Ayurveda Clinic",
  address: 'Nemani bhavan, near Milagris school, office no 4, Salaiwada, Sawantwadi',
  phone: '9067251670',
  email: 'vaidyashwetaayurveda@gmail.com',
  website: 'www.shwetaayurveda.com',
  operatingHours: 'Morning 10 am to 1 pm & Evening 5 pm to 8 pm',
  currency: '₹',
};

export const initialEmailConfig: EmailConfig = {
  smtpEmail: 'vaidyashwetaayurveda@gmail.com',
  smtpAppPassword: '••••••••••••••••',
  smtpServer: 'smtp.gmail.com',
  smtpPort: 587,
  enableNotifications: true,
};

export const initialPatients: Patient[] = [
  {
    id: 'P0003',
    fullName: 'Rajas',
    dob: '2006-05-18',
    age: 20,
    gender: 'Male',
    mobile: '9632541785',
    address: 'Sawantwadi Central',
    bloodGroup: 'A+',
    registrationDate: '2026-05-18',
    lastVisitDate: '2026-06-02',
    totalVisits: 2,
    records: [
      {
        id: 'OPD-2026-003',
        patientId: 'P0003',
        visitDate: '2026-06-02',
        opdType: 'Consultation',
        chargeType: 'First Visit',
        diagnosis: 'Viral pyrexia & joint stiffness',
        symptoms: ['Fever', 'Fatigue', 'Joint stiffness'],
        medicines: [
          {
            id: 'med-1',
            name: 'Maharasnadi yog',
            dosage: '2 tablets',
            frequency: 'Twice daily',
            timing: 'After Food',
            duration: '7 Days',
            instructions: 'With warm water',
          },
          {
            id: 'med-2',
            name: 'Tribhuvan Kirti Ras',
            dosage: '1 tablet',
            frequency: 'Twice daily',
            timing: 'After Food',
            duration: '5 Days',
            instructions: 'With honey / warm water',
          },
        ],
        clinicalNotes: 'Follow-up in 2 days if fever persists.',
        panchakarmaNotes: 'Local Patra Pinda Swedana therapy recommended after acute phase.',
        dietaryAdvice: 'Avoid cold beverages, take light boiled khichdi and warm ginger water.',
        nextVisitDate: '2026-06-04',
        consultationFee: 100,
        medicineFee: 100,
        panchakarmaFee: 100,
        discountType: 'amount',
        discountValue: 10,
        totalFee: 290,
        paymentMode: 'Cash',
        paymentStatus: 'Paid',
        createdAt: '2026-06-02T11:30:00Z',
      },
    ],
  },
  {
    id: 'P0002',
    fullName: 'Omkar',
    dob: '2006-05-06',
    age: 20,
    gender: 'Male',
    mobile: '9685741256',
    address: 'Kudal Road, Sindhudurg',
    bloodGroup: 'B+',
    registrationDate: '2026-05-06',
    lastVisitDate: '2026-05-30',
    totalVisits: 1,
    records: [
      {
        id: 'OPD-2026-002',
        patientId: 'P0002',
        visitDate: '2026-05-30',
        opdType: 'Consultation',
        chargeType: 'First Visit',
        diagnosis: 'Acute fever & Indigestion (Aam Jwara)',
        symptoms: ['Fever', 'Loss of appetite', 'Body ache'],
        medicines: [
          {
            id: 'med-3',
            name: 'Sudarshan Ghanvati',
            dosage: '2 tablets',
            frequency: 'Thrice daily',
            timing: 'After Food',
            duration: '5 Days',
            instructions: 'With lukewarm water',
          },
          {
            id: 'med-4',
            name: 'Mahasudarshan Churna',
            dosage: '3 grams',
            frequency: 'Morning & Night',
            timing: 'After Food',
            duration: '7 Days',
            instructions: 'With lukewarm water',
          },
        ],
        clinicalNotes: 'Vata-Pitta dominant aggravation.',
        panchakarmaNotes: 'Swedana therapy advised next week.',
        dietaryAdvice: 'Moong dal soup, boiled warm water, light diet.',
        nextVisitDate: '2026-06-19',
        consultationFee: 100,
        medicineFee: 100,
        panchakarmaFee: 100,
        discountType: 'amount',
        discountValue: 10,
        totalFee: 290,
        paymentMode: 'UPI',
        paymentStatus: 'Paid',
        createdAt: '2026-05-30T10:15:00Z',
      },
    ],
  },
  {
    id: 'P0001',
    fullName: 'XYZ',
    dob: '2003-05-04',
    age: 23,
    gender: 'Male',
    mobile: '8596324589',
    address: 'Banda, Sawantwadi',
    bloodGroup: 'O+',
    registrationDate: '2026-05-04',
    lastVisitDate: '2026-05-30',
    totalVisits: 1,
    records: [
      {
        id: 'OPD-2026-001',
        patientId: 'P0001',
        visitDate: '2026-05-30',
        opdType: 'Consultation',
        chargeType: 'First Visit',
        diagnosis: 'Hyperacidity (Amlapitta) and Headache',
        symptoms: ['Hyperacidity', 'Headache', 'Burning sensation in chest'],
        medicines: [
          {
            id: 'med-5',
            name: 'Avipattikar Churna',
            dosage: '1 tsp (5g)',
            frequency: 'Twice daily',
            timing: 'Before Food',
            duration: '15 Days',
            instructions: 'With coconut water or ghee',
          },
          {
            id: 'med-6',
            name: 'Kamdudha Ras (Moti Yukta)',
            dosage: '1 tablet',
            frequency: 'Twice daily',
            timing: 'After Food',
            duration: '15 Days',
            instructions: 'With milk / water',
          },
        ],
        clinicalNotes: 'Pitta dosha pacification advised.',
        panchakarmaNotes: 'Takradhara or Virechana suggested if not relieved.',
        dietaryAdvice: 'Avoid spicy, oily, fermented food and excess tea/coffee.',
        nextVisitDate: '2026-06-15',
        consultationFee: 150,
        medicineFee: 149,
        panchakarmaFee: 0,
        discountType: 'amount',
        discountValue: 0,
        totalFee: 299,
        paymentMode: 'Cash',
        paymentStatus: 'Paid',
        createdAt: '2026-05-30T16:00:00Z',
      },
    ],
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'APT-001',
    patientId: 'P0003',
    patientName: 'Rajas',
    patientMobile: '9632541785',
    date: '2026-06-04',
    time: '11:00',
    reason: 'Follow-up for viral fever review',
    type: 'Follow-up Reminder',
    status: 'Scheduled',
    notes: 'Check temperature & joint flexibility',
  },
  {
    id: 'APT-002',
    patientId: 'P0001',
    patientName: 'XYZ',
    patientMobile: '8596324589',
    date: '2026-06-15',
    time: '17:30',
    reason: 'Acidity checkup & medicine refill',
    type: 'Follow-up Reminder',
    status: 'Scheduled',
  },
  {
    id: 'APT-003',
    patientId: 'P0002',
    patientName: 'Omkar',
    patientMobile: '9685741256',
    date: '2026-06-19',
    time: '10:30',
    reason: 'Panchakarma Swedana Session 1',
    type: 'Appointment',
    status: 'Scheduled',
  },
];

export const commonSymptomsList = [
  'Fever',
  'Acute Fever',
  'Headache',
  'Cough & Cold',
  'Dry Cough',
  'Sore Throat',
  'Hyperacidity (Amlapitta)',
  'Indigestion (Ajeerna)',
  'Constipation (Vibandha)',
  'Diarrhea (Atisara)',
  'Joint Pain (Sandhivata)',
  'Lower Back Pain (Katisula)',
  'Cervical Spondylosis (Manyastambha)',
  'Sciatica (Gridhrasi)',
  'Skin Rash / Eczema (Kushtha)',
  'Psoriasis',
  'Acne & Pimples',
  'Hair Fall (Khalitya)',
  'Dandruff (Darunaka)',
  'Insomnia (Anidra)',
  'Fatigue / General Weakness',
  'Loss of Appetite (Aruchi)',
  'Abdominal Cramps / Gas',
  'Nausea & Vomiting',
  'Piles / Hemorrhoids (Arsha)',
  'Fistula / Fissure (Bhagandara / Parikartika)',
  'Hypertension (Raktachapa)',
  'Diabetes Support (Prameha)',
  'Allergic Rhinitis (Pratishyaya)',
  'Asthma / Breathlessness (Tamaka Shwasa)',
  'PCOD / Hormonal Imbalance',
  'Weight Management (Sthaulya)',
];

export const medicineCatalog = [
  { name: 'Maharasnadi yog', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Tribhuvan Kirti Ras', category: 'Ayurvedic', defaultDosage: '1 tab', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With honey or warm water' },
  { name: 'Sudarshan Ghanvati', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Thrice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Mahasudarshan Churna', category: 'Ayurvedic', defaultDosage: '3g', defaultFrequency: 'Morning & Night', defaultTiming: 'After Food', instructions: 'With lukewarm water' },
  { name: 'Avipattikar Churna', category: 'Ayurvedic', defaultDosage: '1 tsp', defaultFrequency: 'Twice daily', defaultTiming: 'Before Food', instructions: 'With coconut water or milk' },
  { name: 'Kamdudha Ras (Moti Yukta)', category: 'Ayurvedic', defaultDosage: '1 tab', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With cold milk or water' },
  { name: 'Ashwagandharishta', category: 'Ayurvedic', defaultDosage: '15 ml', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With equal quantity of water' },
  { name: 'Dashmularishta', category: 'Ayurvedic', defaultDosage: '20 ml', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With equal water' },
  { name: 'Triphala Guggulu', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Yograj Guggulu', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Kaishore Guggulu', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Sitopaladi Churna', category: 'Ayurvedic', defaultDosage: '3g', defaultFrequency: 'Thrice daily', defaultTiming: 'After Food', instructions: 'With pure honey and ghee' },
  { name: 'Talisadi Churna', category: 'Ayurvedic', defaultDosage: '3g', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water or honey' },
  { name: 'Chandraprabha Vati', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With lukewarm water or milk' },
  { name: 'Brahmi Vati (Swarna Yukta)', category: 'Ayurvedic', defaultDosage: '1 tab', defaultFrequency: 'Once daily (Night)', defaultTiming: 'After Food', instructions: 'With warm milk' },
  { name: 'Saraswatarishta', category: 'Ayurvedic', defaultDosage: '15 ml', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With equal water' },
  { name: 'Shankh Bhasma', category: 'Ayurvedic', defaultDosage: '250 mg', defaultFrequency: 'Twice daily', defaultTiming: 'Before Food', instructions: 'With lemon water or honey' },
  { name: 'Arogyavardhini Vati', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Kumaryasava', category: 'Ayurvedic', defaultDosage: '20 ml', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With equal water' },
  { name: 'Gandhak Rasayan', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With milk or warm water' },
  { name: 'Panchatikta Ghrita Guggulu', category: 'Ayurvedic', defaultDosage: '2 tabs', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'With warm water' },
  { name: 'Paracetamol 650mg', category: 'Allopathic', defaultDosage: '1 tab', defaultFrequency: 'As needed / SOS', defaultTiming: 'After Food', instructions: 'For high fever/body pain' },
  { name: 'Pantoprazole 40mg', category: 'Allopathic', defaultDosage: '1 tab', defaultFrequency: 'Once daily (Morning)', defaultTiming: 'Empty Stomach', instructions: 'Take 30 mins before breakfast' },
  { name: 'Cetirizine 10mg', category: 'Allopathic', defaultDosage: '1 tab', defaultFrequency: 'Once daily (Night)', defaultTiming: 'After Food', instructions: 'For allergic itching/running nose' },
  { name: 'Amoxicillin + Clavulanic Acid 625mg', category: 'Allopathic', defaultDosage: '1 tab', defaultFrequency: 'Twice daily', defaultTiming: 'After Food', instructions: 'Complete 5 days antibiotic course' },
];

export const initialDailyNotes: Record<string, string> = {
  '2026-06-02': 'Clinic opened at 9:45 AM. Prepared fresh Dashmula decoction. 3 new OPD consultations completed.',
  '2026-06-03': 'Check stock for Maharasnadi yog and Sudarshan Ghanvati bottles. Panchakarma room sanitization done.',
  '2026-06-04': 'Rajas (P0003) follow-up visit scheduled for 11:00 AM.',
};

